name: 🚀 Build

on: push
    pull_request

jobs:
    build-deploy:
        name: 🎉 Build and Deploy

        runs-on: ubuntu-latest

        steps:
            - name: 🚚 Get latest code
              uses: actions/checkout@v2.3.4

            - name: 🔨 Set up Node 14.16.1
              uses: actions/setup-node@v2
              with:
                  node-version: 14.16.1

            - name: 🛠 Compile Backend
              run: |
                  cd server
                  npm ci
                  npm run tsc
                  cd ..

            - name: ⛏ Build Frontend
              run: |
                  cd client
                  npm ci
                  npm run build
                  cd ..
